pub const Operation = enum {
    adc,
    and_,
    asl,
    bcc,
    bcs,
    beq,
    bit,
    bmi,
    bne,
    bpl,
    bra,
    brk,
    brl,
    bvc,
    bvs,
    clc,
    cld,
    cli,
    clv,
    cmp,
    cop,
    cpx,
    cpy,
    dec,
    dex,
    dey,
    eor,
    inc,
    inx,
    iny,
    jml,
    jmp,
    jsl,
    jsr,
    lda,
    ldx,
    ldy,
    lsr,
    mvn,
    mvp,
    nop,
    ora,
    pea,
    pei,
    per,
    pha,
    phb,
    phd,
    phk,
    php,
    phx,
    phy,
    pla,
    plb,
    pld,
    plp,
    plx,
    ply,
    rep,
    rol,
    ror,
    rti,
    rtl,
    rts,
    sbc,
    sec,
    sed,
    sei,
    sep,
    sta,
    stp,
    stx,
    sty,
    stz,
    tax,
    tay,
    tcd,
    tcs,
    tdc,
    trb,
    tsb,
    tsc,
    tsx,
    txa,
    txs,
    txy,
    tya,
    tyx,
    wai,
    wdm,
    xba,
    xce,
};

pub const Addressing = enum {
    implied,
    accumulator,
    immediate8,
    immediate_m,
    immediate_x,
    direct,
    direct_x,
    direct_y,
    direct_indirect,
    direct_indexed_indirect,
    direct_indirect_indexed,
    direct_indirect_long,
    direct_indirect_long_y,
    stack_relative,
    stack_relative_indirect_y,
    absolute,
    absolute_x,
    absolute_y,
    absolute_long,
    absolute_long_x,
    relative8,
    relative16,
    absolute_indirect,
    absolute_indexed_indirect,
    absolute_indirect_long,
    block_move,
};

pub const Width = enum {
    none,
    accumulator,
    index,
};

pub const Descriptor = struct {
    operation: Operation,
    addressing: Addressing,
    width: Width = .none,
};

const D = Descriptor;

// The W65C816 defines all 256 opcode bytes. Keeping the decode truth in one
// table makes coverage generation mechanical and prevents a host-language
// switch default from silently becoming an undocumented guest opcode.
pub const table = [256]Descriptor{
    D{ .operation = .brk, .addressing = .immediate8 },
    D{ .operation = .ora, .addressing = .direct_indexed_indirect, .width = .accumulator },
    D{ .operation = .cop, .addressing = .immediate8 },
    D{ .operation = .ora, .addressing = .stack_relative, .width = .accumulator },
    D{ .operation = .tsb, .addressing = .direct, .width = .accumulator },
    D{ .operation = .ora, .addressing = .direct, .width = .accumulator },
    D{ .operation = .asl, .addressing = .direct, .width = .accumulator },
    D{ .operation = .ora, .addressing = .direct_indirect_long, .width = .accumulator },
    D{ .operation = .php, .addressing = .implied },
    D{ .operation = .ora, .addressing = .immediate_m, .width = .accumulator },
    D{ .operation = .asl, .addressing = .accumulator, .width = .accumulator },
    D{ .operation = .phd, .addressing = .implied },
    D{ .operation = .tsb, .addressing = .absolute, .width = .accumulator },
    D{ .operation = .ora, .addressing = .absolute, .width = .accumulator },
    D{ .operation = .asl, .addressing = .absolute, .width = .accumulator },
    D{ .operation = .ora, .addressing = .absolute_long, .width = .accumulator },

    D{ .operation = .bpl, .addressing = .relative8 },
    D{ .operation = .ora, .addressing = .direct_indirect_indexed, .width = .accumulator },
    D{ .operation = .ora, .addressing = .direct_indirect, .width = .accumulator },
    D{ .operation = .ora, .addressing = .stack_relative_indirect_y, .width = .accumulator },
    D{ .operation = .trb, .addressing = .direct, .width = .accumulator },
    D{ .operation = .ora, .addressing = .direct_x, .width = .accumulator },
    D{ .operation = .asl, .addressing = .direct_x, .width = .accumulator },
    D{ .operation = .ora, .addressing = .direct_indirect_long_y, .width = .accumulator },
    D{ .operation = .clc, .addressing = .implied },
    D{ .operation = .ora, .addressing = .absolute_y, .width = .accumulator },
    D{ .operation = .inc, .addressing = .accumulator, .width = .accumulator },
    D{ .operation = .tcs, .addressing = .implied },
    D{ .operation = .trb, .addressing = .absolute, .width = .accumulator },
    D{ .operation = .ora, .addressing = .absolute_x, .width = .accumulator },
    D{ .operation = .asl, .addressing = .absolute_x, .width = .accumulator },
    D{ .operation = .ora, .addressing = .absolute_long_x, .width = .accumulator },

    D{ .operation = .jsr, .addressing = .absolute },
    D{ .operation = .and_, .addressing = .direct_indexed_indirect, .width = .accumulator },
    D{ .operation = .jsl, .addressing = .absolute_long },
    D{ .operation = .and_, .addressing = .stack_relative, .width = .accumulator },
    D{ .operation = .bit, .addressing = .direct, .width = .accumulator },
    D{ .operation = .and_, .addressing = .direct, .width = .accumulator },
    D{ .operation = .rol, .addressing = .direct, .width = .accumulator },
    D{ .operation = .and_, .addressing = .direct_indirect_long, .width = .accumulator },
    D{ .operation = .plp, .addressing = .implied },
    D{ .operation = .and_, .addressing = .immediate_m, .width = .accumulator },
    D{ .operation = .rol, .addressing = .accumulator, .width = .accumulator },
    D{ .operation = .pld, .addressing = .implied },
    D{ .operation = .bit, .addressing = .absolute, .width = .accumulator },
    D{ .operation = .and_, .addressing = .absolute, .width = .accumulator },
    D{ .operation = .rol, .addressing = .absolute, .width = .accumulator },
    D{ .operation = .and_, .addressing = .absolute_long, .width = .accumulator },

    D{ .operation = .bmi, .addressing = .relative8 },
    D{ .operation = .and_, .addressing = .direct_indirect_indexed, .width = .accumulator },
    D{ .operation = .and_, .addressing = .direct_indirect, .width = .accumulator },
    D{ .operation = .and_, .addressing = .stack_relative_indirect_y, .width = .accumulator },
    D{ .operation = .bit, .addressing = .direct_x, .width = .accumulator },
    D{ .operation = .and_, .addressing = .direct_x, .width = .accumulator },
    D{ .operation = .rol, .addressing = .direct_x, .width = .accumulator },
    D{ .operation = .and_, .addressing = .direct_indirect_long_y, .width = .accumulator },
    D{ .operation = .sec, .addressing = .implied },
    D{ .operation = .and_, .addressing = .absolute_y, .width = .accumulator },
    D{ .operation = .dec, .addressing = .accumulator, .width = .accumulator },
    D{ .operation = .tsc, .addressing = .implied },
    D{ .operation = .bit, .addressing = .absolute_x, .width = .accumulator },
    D{ .operation = .and_, .addressing = .absolute_x, .width = .accumulator },
    D{ .operation = .rol, .addressing = .absolute_x, .width = .accumulator },
    D{ .operation = .and_, .addressing = .absolute_long_x, .width = .accumulator },

    D{ .operation = .rti, .addressing = .implied },
    D{ .operation = .eor, .addressing = .direct_indexed_indirect, .width = .accumulator },
    D{ .operation = .wdm, .addressing = .immediate8 },
    D{ .operation = .eor, .addressing = .stack_relative, .width = .accumulator },
    D{ .operation = .mvp, .addressing = .block_move, .width = .index },
    D{ .operation = .eor, .addressing = .direct, .width = .accumulator },
    D{ .operation = .lsr, .addressing = .direct, .width = .accumulator },
    D{ .operation = .eor, .addressing = .direct_indirect_long, .width = .accumulator },
    D{ .operation = .pha, .addressing = .implied, .width = .accumulator },
    D{ .operation = .eor, .addressing = .immediate_m, .width = .accumulator },
    D{ .operation = .lsr, .addressing = .accumulator, .width = .accumulator },
    D{ .operation = .phk, .addressing = .implied },
    D{ .operation = .jmp, .addressing = .absolute },
    D{ .operation = .eor, .addressing = .absolute, .width = .accumulator },
    D{ .operation = .lsr, .addressing = .absolute, .width = .accumulator },
    D{ .operation = .eor, .addressing = .absolute_long, .width = .accumulator },

    D{ .operation = .bvc, .addressing = .relative8 },
    D{ .operation = .eor, .addressing = .direct_indirect_indexed, .width = .accumulator },
    D{ .operation = .eor, .addressing = .direct_indirect, .width = .accumulator },
    D{ .operation = .eor, .addressing = .stack_relative_indirect_y, .width = .accumulator },
    D{ .operation = .mvn, .addressing = .block_move, .width = .index },
    D{ .operation = .eor, .addressing = .direct_x, .width = .accumulator },
    D{ .operation = .lsr, .addressing = .direct_x, .width = .accumulator },
    D{ .operation = .eor, .addressing = .direct_indirect_long_y, .width = .accumulator },
    D{ .operation = .cli, .addressing = .implied },
    D{ .operation = .eor, .addressing = .absolute_y, .width = .accumulator },
    D{ .operation = .phy, .addressing = .implied, .width = .index },
    D{ .operation = .tcd, .addressing = .implied },
    D{ .operation = .jml, .addressing = .absolute_long },
    D{ .operation = .eor, .addressing = .absolute_x, .width = .accumulator },
    D{ .operation = .lsr, .addressing = .absolute_x, .width = .accumulator },
    D{ .operation = .eor, .addressing = .absolute_long_x, .width = .accumulator },

    D{ .operation = .rts, .addressing = .implied },
    D{ .operation = .adc, .addressing = .direct_indexed_indirect, .width = .accumulator },
    D{ .operation = .per, .addressing = .relative16 },
    D{ .operation = .adc, .addressing = .stack_relative, .width = .accumulator },
    D{ .operation = .stz, .addressing = .direct, .width = .accumulator },
    D{ .operation = .adc, .addressing = .direct, .width = .accumulator },
    D{ .operation = .ror, .addressing = .direct, .width = .accumulator },
    D{ .operation = .adc, .addressing = .direct_indirect_long, .width = .accumulator },
    D{ .operation = .pla, .addressing = .implied, .width = .accumulator },
    D{ .operation = .adc, .addressing = .immediate_m, .width = .accumulator },
    D{ .operation = .ror, .addressing = .accumulator, .width = .accumulator },
    D{ .operation = .rtl, .addressing = .implied },
    D{ .operation = .jmp, .addressing = .absolute_indirect },
    D{ .operation = .adc, .addressing = .absolute, .width = .accumulator },
    D{ .operation = .ror, .addressing = .absolute, .width = .accumulator },
    D{ .operation = .adc, .addressing = .absolute_long, .width = .accumulator },

    D{ .operation = .bvs, .addressing = .relative8 },
    D{ .operation = .adc, .addressing = .direct_indirect_indexed, .width = .accumulator },
    D{ .operation = .adc, .addressing = .direct_indirect, .width = .accumulator },
    D{ .operation = .adc, .addressing = .stack_relative_indirect_y, .width = .accumulator },
    D{ .operation = .stz, .addressing = .direct_x, .width = .accumulator },
    D{ .operation = .adc, .addressing = .direct_x, .width = .accumulator },
    D{ .operation = .ror, .addressing = .direct_x, .width = .accumulator },
    D{ .operation = .adc, .addressing = .direct_indirect_long_y, .width = .accumulator },
    D{ .operation = .sei, .addressing = .implied },
    D{ .operation = .adc, .addressing = .absolute_y, .width = .accumulator },
    D{ .operation = .ply, .addressing = .implied, .width = .index },
    D{ .operation = .tdc, .addressing = .implied },
    D{ .operation = .jmp, .addressing = .absolute_indexed_indirect },
    D{ .operation = .adc, .addressing = .absolute_x, .width = .accumulator },
    D{ .operation = .ror, .addressing = .absolute_x, .width = .accumulator },
    D{ .operation = .adc, .addressing = .absolute_long_x, .width = .accumulator },

    D{ .operation = .bra, .addressing = .relative8 },
    D{ .operation = .sta, .addressing = .direct_indexed_indirect, .width = .accumulator },
    D{ .operation = .brl, .addressing = .relative16 },
    D{ .operation = .sta, .addressing = .stack_relative, .width = .accumulator },
    D{ .operation = .sty, .addressing = .direct, .width = .index },
    D{ .operation = .sta, .addressing = .direct, .width = .accumulator },
    D{ .operation = .stx, .addressing = .direct, .width = .index },
    D{ .operation = .sta, .addressing = .direct_indirect_long, .width = .accumulator },
    D{ .operation = .dey, .addressing = .implied, .width = .index },
    D{ .operation = .bit, .addressing = .immediate_m, .width = .accumulator },
    D{ .operation = .txa, .addressing = .implied, .width = .accumulator },
    D{ .operation = .phb, .addressing = .implied },
    D{ .operation = .sty, .addressing = .absolute, .width = .index },
    D{ .operation = .sta, .addressing = .absolute, .width = .accumulator },
    D{ .operation = .stx, .addressing = .absolute, .width = .index },
    D{ .operation = .sta, .addressing = .absolute_long, .width = .accumulator },

    D{ .operation = .bcc, .addressing = .relative8 },
    D{ .operation = .sta, .addressing = .direct_indirect_indexed, .width = .accumulator },
    D{ .operation = .sta, .addressing = .direct_indirect, .width = .accumulator },
    D{ .operation = .sta, .addressing = .stack_relative_indirect_y, .width = .accumulator },
    D{ .operation = .sty, .addressing = .direct_x, .width = .index },
    D{ .operation = .sta, .addressing = .direct_x, .width = .accumulator },
    D{ .operation = .stx, .addressing = .direct_y, .width = .index },
    D{ .operation = .sta, .addressing = .direct_indirect_long_y, .width = .accumulator },
    D{ .operation = .tya, .addressing = .implied, .width = .accumulator },
    D{ .operation = .sta, .addressing = .absolute_y, .width = .accumulator },
    D{ .operation = .txs, .addressing = .implied },
    D{ .operation = .txy, .addressing = .implied, .width = .index },
    D{ .operation = .stz, .addressing = .absolute, .width = .accumulator },
    D{ .operation = .sta, .addressing = .absolute_x, .width = .accumulator },
    D{ .operation = .stz, .addressing = .absolute_x, .width = .accumulator },
    D{ .operation = .sta, .addressing = .absolute_long_x, .width = .accumulator },

    D{ .operation = .ldy, .addressing = .immediate_x, .width = .index },
    D{ .operation = .lda, .addressing = .direct_indexed_indirect, .width = .accumulator },
    D{ .operation = .ldx, .addressing = .immediate_x, .width = .index },
    D{ .operation = .lda, .addressing = .stack_relative, .width = .accumulator },
    D{ .operation = .ldy, .addressing = .direct, .width = .index },
    D{ .operation = .lda, .addressing = .direct, .width = .accumulator },
    D{ .operation = .ldx, .addressing = .direct, .width = .index },
    D{ .operation = .lda, .addressing = .direct_indirect_long, .width = .accumulator },
    D{ .operation = .tay, .addressing = .implied, .width = .index },
    D{ .operation = .lda, .addressing = .immediate_m, .width = .accumulator },
    D{ .operation = .tax, .addressing = .implied, .width = .index },
    D{ .operation = .plb, .addressing = .implied },
    D{ .operation = .ldy, .addressing = .absolute, .width = .index },
    D{ .operation = .lda, .addressing = .absolute, .width = .accumulator },
    D{ .operation = .ldx, .addressing = .absolute, .width = .index },
    D{ .operation = .lda, .addressing = .absolute_long, .width = .accumulator },

    D{ .operation = .bcs, .addressing = .relative8 },
    D{ .operation = .lda, .addressing = .direct_indirect_indexed, .width = .accumulator },
    D{ .operation = .lda, .addressing = .direct_indirect, .width = .accumulator },
    D{ .operation = .lda, .addressing = .stack_relative_indirect_y, .width = .accumulator },
    D{ .operation = .ldy, .addressing = .direct_x, .width = .index },
    D{ .operation = .lda, .addressing = .direct_x, .width = .accumulator },
    D{ .operation = .ldx, .addressing = .direct_y, .width = .index },
    D{ .operation = .lda, .addressing = .direct_indirect_long_y, .width = .accumulator },
    D{ .operation = .clv, .addressing = .implied },
    D{ .operation = .lda, .addressing = .absolute_y, .width = .accumulator },
    D{ .operation = .tsx, .addressing = .implied, .width = .index },
    D{ .operation = .tyx, .addressing = .implied, .width = .index },
    D{ .operation = .ldy, .addressing = .absolute_x, .width = .index },
    D{ .operation = .lda, .addressing = .absolute_x, .width = .accumulator },
    D{ .operation = .ldx, .addressing = .absolute_y, .width = .index },
    D{ .operation = .lda, .addressing = .absolute_long_x, .width = .accumulator },

    D{ .operation = .cpy, .addressing = .immediate_x, .width = .index },
    D{ .operation = .cmp, .addressing = .direct_indexed_indirect, .width = .accumulator },
    D{ .operation = .rep, .addressing = .immediate8 },
    D{ .operation = .cmp, .addressing = .stack_relative, .width = .accumulator },
    D{ .operation = .cpy, .addressing = .direct, .width = .index },
    D{ .operation = .cmp, .addressing = .direct, .width = .accumulator },
    D{ .operation = .dec, .addressing = .direct, .width = .accumulator },
    D{ .operation = .cmp, .addressing = .direct_indirect_long, .width = .accumulator },
    D{ .operation = .iny, .addressing = .implied, .width = .index },
    D{ .operation = .cmp, .addressing = .immediate_m, .width = .accumulator },
    D{ .operation = .dex, .addressing = .implied, .width = .index },
    D{ .operation = .wai, .addressing = .implied },
    D{ .operation = .cpy, .addressing = .absolute, .width = .index },
    D{ .operation = .cmp, .addressing = .absolute, .width = .accumulator },
    D{ .operation = .dec, .addressing = .absolute, .width = .accumulator },
    D{ .operation = .cmp, .addressing = .absolute_long, .width = .accumulator },

    D{ .operation = .bne, .addressing = .relative8 },
    D{ .operation = .cmp, .addressing = .direct_indirect_indexed, .width = .accumulator },
    D{ .operation = .cmp, .addressing = .direct_indirect, .width = .accumulator },
    D{ .operation = .cmp, .addressing = .stack_relative_indirect_y, .width = .accumulator },
    D{ .operation = .pei, .addressing = .direct_indirect },
    D{ .operation = .cmp, .addressing = .direct_x, .width = .accumulator },
    D{ .operation = .dec, .addressing = .direct_x, .width = .accumulator },
    D{ .operation = .cmp, .addressing = .direct_indirect_long_y, .width = .accumulator },
    D{ .operation = .cld, .addressing = .implied },
    D{ .operation = .cmp, .addressing = .absolute_y, .width = .accumulator },
    D{ .operation = .phx, .addressing = .implied, .width = .index },
    D{ .operation = .stp, .addressing = .implied },
    D{ .operation = .jmp, .addressing = .absolute_indirect_long },
    D{ .operation = .cmp, .addressing = .absolute_x, .width = .accumulator },
    D{ .operation = .dec, .addressing = .absolute_x, .width = .accumulator },
    D{ .operation = .cmp, .addressing = .absolute_long_x, .width = .accumulator },

    D{ .operation = .cpx, .addressing = .immediate_x, .width = .index },
    D{ .operation = .sbc, .addressing = .direct_indexed_indirect, .width = .accumulator },
    D{ .operation = .sep, .addressing = .immediate8 },
    D{ .operation = .sbc, .addressing = .stack_relative, .width = .accumulator },
    D{ .operation = .cpx, .addressing = .direct, .width = .index },
    D{ .operation = .sbc, .addressing = .direct, .width = .accumulator },
    D{ .operation = .inc, .addressing = .direct, .width = .accumulator },
    D{ .operation = .sbc, .addressing = .direct_indirect_long, .width = .accumulator },
    D{ .operation = .inx, .addressing = .implied, .width = .index },
    D{ .operation = .sbc, .addressing = .immediate_m, .width = .accumulator },
    D{ .operation = .nop, .addressing = .implied },
    D{ .operation = .xba, .addressing = .implied },
    D{ .operation = .cpx, .addressing = .absolute, .width = .index },
    D{ .operation = .sbc, .addressing = .absolute, .width = .accumulator },
    D{ .operation = .inc, .addressing = .absolute, .width = .accumulator },
    D{ .operation = .sbc, .addressing = .absolute_long, .width = .accumulator },

    D{ .operation = .beq, .addressing = .relative8 },
    D{ .operation = .sbc, .addressing = .direct_indirect_indexed, .width = .accumulator },
    D{ .operation = .sbc, .addressing = .direct_indirect, .width = .accumulator },
    D{ .operation = .sbc, .addressing = .stack_relative_indirect_y, .width = .accumulator },
    D{ .operation = .pea, .addressing = .absolute },
    D{ .operation = .sbc, .addressing = .direct_x, .width = .accumulator },
    D{ .operation = .inc, .addressing = .direct_x, .width = .accumulator },
    D{ .operation = .sbc, .addressing = .direct_indirect_long_y, .width = .accumulator },
    D{ .operation = .sed, .addressing = .implied },
    D{ .operation = .sbc, .addressing = .absolute_y, .width = .accumulator },
    D{ .operation = .plx, .addressing = .implied, .width = .index },
    D{ .operation = .xce, .addressing = .implied },
    D{ .operation = .jsr, .addressing = .absolute_indexed_indirect },
    D{ .operation = .sbc, .addressing = .absolute_x, .width = .accumulator },
    D{ .operation = .inc, .addressing = .absolute_x, .width = .accumulator },
    D{ .operation = .sbc, .addressing = .absolute_long_x, .width = .accumulator },
};

pub fn descriptor(opcode: u8) Descriptor {
    return table[opcode];
}
